/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Sticker = IDL.Record({
  'id' : IDL.Text,
  'pinterestLink' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'amazonLink' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSticker' : IDL.Func([Sticker], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSticker' : IDL.Func([IDL.Text], [], []),
  'getAllStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
  'getStickerById' : IDL.Func([IDL.Text], [IDL.Opt(Sticker)], ['query']),
  'getStickersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Sticker)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedStickers' : IDL.Func([], [], []),
  'toggleFeatured' : IDL.Func([IDL.Text], [], []),
  'updateSticker' : IDL.Func([Sticker], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Sticker = IDL.Record({
    'id' : IDL.Text,
    'pinterestLink' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'amazonLink' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSticker' : IDL.Func([Sticker], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSticker' : IDL.Func([IDL.Text], [], []),
    'getAllStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
    'getStickerById' : IDL.Func([IDL.Text], [IDL.Opt(Sticker)], ['query']),
    'getStickersByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Sticker)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedStickers' : IDL.Func([], [], []),
    'toggleFeatured' : IDL.Func([IDL.Text], [], []),
    'updateSticker' : IDL.Func([Sticker], [], []),
  });
};

export const init = ({ IDL }) => { return []; };